### ISSUE TITLE
Linting on the fly

### ISSUE THREAD

**Issue by dapetcu21** [AtomLinter/linter-clang#119]
I remember running YCM in vim and it would do this. It would lint on the fly. It's doable if we pipe the editor's content to clang. If performance is an issue, it could come as a configuration parameter. I'm willing to write a PR for this when I'll have time.

**Comment by BosJ** [comment]
+1. It only lints on save, despite the fact that I have "Lint As You Type" checked.

**Comment by Arcanemagus** [comment]
@BosJ this linter marks itself as not (currently) compatible with lintOnFly, as such the `linter` package only executes it on save.

To support this either the current file contents would need to be sent to clang via stdin if it support that, or a temporary file will need to be generated with the current contents and that linted. I'm sure @kepler0 would appreciate a PR implementing this if one of you wants to take it on :wink:.

**Comment by dapetcu21** [comment]
I'd love to do this, but I'm currently swamped for the foreseeable future :(

**Comment by Arcanemagus** [comment]
Just a note: This is a _very_ tricky thing to get right when the code potentially depends on external files like this does. Personally I don't think it is worth the mass of bug reports this will bring in, especially since compiling is a process that will take a while (while: more than a few hundred ms in this case) in the first place.
