### ISSUE TITLE
Linter errors not extended across all characters in the buffer relevant to the error

### ISSUE THREAD

**Issue by eboracus** [AtomLinter/linter-clang#147]
It seems that linter errors are only being displayed as a single point at one character's location in the code, whereas warnings are shown extending across the full range relevant to the warning, as expected.

Briefly checking other languages I see errors extending across the expected range, so am thinking this could be `linter-clang` specific?

In this example I would expect the error to stretch across the whole variable name, as it's an undefined variable, the same as is the case for the warning:

![linter_errorunderline](https://cloud.githubusercontent.com/assets/11758299/14588921/9de22b5e-04cd-11e6-8bea-b834deb33738.gif)

I've not tried testing for every 'type' of error/warning, so I don't know if this is only for some or all. Do others see this same behaviour?

**Comment by Arcanemagus** [comment]
It looks like clang may or may not provide end ranges for messages, depending on the message. Since this plugin is currently just using a [regex](https://github.com/AtomLinter/linter-clang/blob/v3.4.4/lib/main.js#L54) to parse the output and nothing more, when no end range is found it simply uses the single start character.

If somebody wants to put together a PR moving this to use `rangeFromLineNumber` if no end column is specified I'd be happy to review it.
