### ISSUE TITLE
Why the cwd fix still not applied?

### ISSUE THREAD

**Issue by FirstTimeInForever** [AtomLinter/linter-clang#149]
I have not used Atom for a long time and when I tried it again I was surprised that the current working directory still not fixed. I opened the issue six months ago. I guess you just forget about this problem. I found that the solution is already written but not merged. Please merge this: https://github.com/AtomLinter/linter-clang/tree/current_working_directory
Thanks.

**Comment by keplersj** [comment]
Funny you should say that. When I fixed it six months ago, I asked for your feedback before merging and you never gave it. So it was never merged.

Btw, because a issue for this already exists and you've interacted with it before I consider this new issue an abuse of GitHub Issue Tickets. The most appropriate and helpful action would've been to respond on the previous ticket - rather than creating a new condescending ticket.
