### ISSUE TITLE
Invalid flag -fdiagnostics-absolute-paths

### ISSUE THREAD

**Issue by nick-prat** [AtomLinter/linter-clang#199]
Invalid flag that causes clang to error out and not report any errors or warnings.

Clang is version 3.9.0 on Ubuntu 16.10

edit: The flag isn't in the documentation for 3.9 or 3.8, and only appears in 5.0 under clang-cl which is described as
> clang-cl is an alternative command-line interface to Clang, designed for compatibility with the Visual C++ compiler, cl.exe.

This sounds like it might be a problem for linux and mac. Possibly disable this flag on non windows machines?

**Comment by Arcanemagus** [comment]
I was testing on clang v4.0.0, the current stable release, you can find it in [the documentation](http://releases.llvm.org/4.0.0/tools/clang/docs/UsersManual.html#id86) for that version.

Since this version is somewhat new though, it looks like we're going to have to have a fallback for systems that aren't current.

**Comment by db47h** [comment]
Pushing for clang 4.0 is very likely to be problematic for many users for a good while. It just came out last month and  most Linux users will just wait for their distro to upgrade. Just for Ubuntu, clang 4.0 won't be "current" before zesty comes out sometimes this month, and LTS users (a lot of corporate users) will stay on clang 3.8 until 2018/04.

**Comment by matteodelabre** [comment]
It’s problematic that the package doesn’t output anything to the user in the case where the installed clang version doesn’t support the flag. In my opinion, it should:

* parse the error output from clang, detect when clang reports that a flag isn’t supported, and reissue the command without the problematic flag;
* display a generic error message in case clang reports an error that is not supported by the package.

Currently, it acts as a kind of pass-through when clang reports an error, because it doesn’t match the regular expression (at https://github.com/AtomLinter/linter-clang/blob/master/lib/main.js#L259).

**Comment by Arcanemagus** [comment]
@matteodelabre You can blame that on `clang`'s "interesting" decision to only output on `stderr` so there is no way to know what is valid output and what is an error that we simply aren't parsing. If you have a solution I'd be happy to review a PR as I don't use this linter myself.

**Comment by Arcanemagus** [comment]
v4.1.1 is published which should fix this package for `clang` versions below v4.0.0.

**Comment by vlasenkov** [comment]
update to 4.1.1 caused this:

<img width="684" alt="screen shot 2017-04-03 at 20 52 25" src="https://cloud.githubusercontent.com/assets/13369474/24622978/94eb89ae-18af-11e7-8267-b84d40a4df71.png">

**Comment by Arcanemagus** [comment]
@vlasenkov Those errors have nothing to do with this package. Are you getting any messages in the console when attempting to lint a file?
