### ISSUE TITLE
Linter lints .h files as C++ instead of C.

### ISSUE THREAD

**Issue by TSnake41** [AtomLinter/linter-clang#215]
So, that can cause some errors for example with implicit void pointer casting (which is perfectly valid in C) and also odd errors with restrict keyword valid in C99.

### How to reproduce :
in foo.h
```c
const void *bar(const char *restrict s);

void foo(void)
{
    const char *a = "a";
    const int *b = bar(a);
}
```
Got
```
Error	clang	expected ')'	1:38
Error	clang	cannot initialize a variable of type 'const int *' with an rvalue of type 'const void *'	6:20
Warning	clang	to match this '('	1:16
```

**Comment by Arcanemagus** [comment]
This is actually _exactly_ what you are telling it to do 😉.

By default Atom opens `.h` files as C++ because too many developers are lazy and don't use the proper `.hpp` extension, so it has to make an assumption and for your particular case it's assuming wrong. You can see this in the lower right where it shows the language as `C++`.

You can override which language by customizing the `.h` file extension to recognize as `source.c`:
http://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition
