### ISSUE TITLE
Enhancement request - automatically add to PATH

### ISSUE THREAD

**Issue by thecolORadokid** [AtomLinter/linter-clang#239]
First off I love clang, just as something I think would make it better would be to have a prompt or an easy way to add this to the environment path. I was getting errors trying to use it at first, but then looked in the developer console and saw the error. This isn't something that I am used to doing with other Atom packages. Thank you!

**Comment by Filliny** [comment]
Please - what error u get and how to fix it? My clang totally not working (even if other lint modules works fine). I have gcc PATH added (minGW)... what else? Thx

**Comment by Arcanemagus** [comment]
> This isn't something that I am used to doing with other Atom packages.

Most Atom packages don't rely on external tools, of the ones that do they _all_ either require to you to have added the tool to the `PATH`, provide a way to specify the path directly, or both (like this package).

Since this isn't really something to do with this package I'm going to close this issue.

----

@Filliny this is a wrapper around `clang`, not `gcc`. You should either look into [linter-gcc2](https://atom.io/packages/linter-gcc2), or install [`clang`](https://clang.llvm.org/) if this is what you are looking for.
