### ISSUE TITLE
linter-clang ignores *.h files in c++ mode

### ISSUE THREAD

**Issue by fbbdev** [AtomLinter/linter-clang#57]
When I open a C++ header file with extension .h linter-clang does not parse it. It works correctly with hpp files.

**Comment by k2b6s9j** [comment]
This most likely has to do with all C, C++, Objective-C, and Objective-C++ grammars claiming '.h' files for theirs. If you could post some example files, a working C++ header and a C++ header with a error ideally, I'd be happy to poke around and see what could be done.

Most likely though the solution is to tell Atom which Grammar the header actually works with.

**Comment by fbbdev** [comment]
Setting the grammar manually does not fix the issue. I will send you some samples tomorrow.
BTW, I'm using clang 3.5 and 3.6... I don't know if this matters.

**Comment by k2b6s9j** [comment]
Shouldn't matter. It would only matter if they change the way they display errors in the console.

**Comment by jgiokas** [comment]
Hi, I encountered the same issue a few days ago. I think the cause of the problem is the order of arguments in clang. If you open the atom in dev mode we will see that the file to be parsed is the first argument. I played a bit with the code and tried to put it last. It worked. You have also to explicitly set the file grammar to C++ (from the bottom right of the atom window). Let me know if it works for you.

**Comment by fbbdev** [comment]
Here are four header files demonstrating the issue.
[c_ok.h](https://gist.github.com/fbbdev/31468380dd144c8bb46d/raw/2dc62dc100aa87ac7038dc75afb069ec3a6c357f/c_ok.h)
[c_error.h](https://gist.github.com/fbbdev/31468380dd144c8bb46d/raw/bfe06b4d6611d5b6e7b26e146fc23efbe6568d57/c_error.h)
[cpp_ok.h](https://gist.github.com/fbbdev/31468380dd144c8bb46d/raw/c91a9bbbe70378ded31d0a7ab2ead3bf9fd83346/cpp_ok.h)
[cpp_error.h](https://gist.github.com/fbbdev/31468380dd144c8bb46d/raw/7f9c58bab4530157daed5db6f3430880146fa288/cpp_error.h)

@jgiokas your trick solves the issue, but your pull request will break linter-clang when the "Clang Command" config string (`linter-clang.clangCommand`) contains spaces.

**Comment by jgiokas** [comment]
You are right. I just wanted to provide a quick workaround, didn't give much thought about it. So, in order to make it work either the logic of getCmdAndArgs in linter.coffee should change or we should handle the case where the "Clang Command" config string (linter-clang.clangCommand) contains spaces? Don't know which is better to do.

**Comment by fbbdev** [comment]
I think the `linter-clang.clangCommand` option should not contain arguments (they should go in the additional flag options). The solution would then be to make `@cmd` an array. This gives two benefits:
 - You can put clang in paths with spaces
 - The first item in args will always be the file path

I am preparing a pull request.

**Comment by fbbdev** [comment]
Created pull request: #59
