### ISSUE TITLE
Include path

### ISSUE THREAD

**Issue by WSoS** [AtomLinter/linter-clang#81]
if we put the include path in the file .linter-clang-includes, it works, but if we put the include path in the setting of the package, it does not work

**Comment by k2b6s9j** [comment]
After I finish porting the linter to the [new API](https://github.com/AtomLinter/linter-plus) I will be redoing the way the linter handles include files like this in a manner that makes much more sense, so that odd corner case issues like this do not occur. Be on the watch for this once the new API is released soon.

**Comment by k2b6s9j** [comment]
In the settings of the package you can now set include paths separated by comma. These paths will be global with all instances of the linter.

As for the removal of `.linter-clang-includes` please transition to a `.clang_complete` file.
